name: Build Package ARM64 (Reusable)

on:
  workflow_call:
    inputs:
      build_flags:
        description: 'Flags to pass to build.sh (e.g., "--build appimage --clean no")'
        required: false
        type: string
        default: '' # Default is no extra flags
      artifact_suffix:
        description: 'Suffix for the artifact name (e.g., deb, appimage)'
        required: true
        type: string

jobs:
  build:
    # Use an ARM64 runner
    runs-on: ubuntu-22.04-arm64

    steps:
    # Checkout code is needed within the reusable workflow itself
    - name: Checkout repository
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse2 icoutils imagemagick p7zip-full wget

    - name: Make build script executable
      run: chmod +x ./build.sh

    - name: Run build script
      run: |
        echo "Running ARM64 build with flags: ${{ inputs.build_flags }}"
        # No sudo needed if runner user has permissions or build.sh handles it internally
        ./build.sh ${{ inputs.build_flags }}

    # Upload the built artifact for the release job
    - name: Upload ARM64 Artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: package-arm64-${{ inputs.artifact_suffix }} # Unique name using suffix
        path: | # Adjust path based on expected output
          claude-desktop_*.deb
          claude-desktop-*.AppImage
          claude-desktop-*.AppImage.zsync
        if-no-files-found: error # Fail if build didn't produce output